### ISSUE TITLE
Error during add a blog entry with plone 5.0.6 add image

### ISSUE THREAD

**Issue by mactrash** [collective/collective.blog#3]
@pcdummy Can you help to do a quick fix of this?

Traceback (most recent call last):
  File "/opt/plone/buildout-cache/eggs/plone.namedfile-3.0.9-py2.7.egg/plone/namedfile/scaling.py", line 290, in create
    **parameters)
  File "/opt/plone/buildout-cache/eggs/plone.scale-1.4.1-py2.7.egg/plone/scale/scale.py", line 31, in scaleImage
    image = PIL.Image.open(image)
  File "/opt/plone/buildout-cache/eggs/Pillow-3.4.2-py2.7-linux-x86_64.egg/PIL/Image.py", line 2287, in open
    fp = io.BytesIO(fp.read())
AttributeError: read

**Comment by jonaspiterek** [comment]
Closing because of deprecation.
